### PR TITLE
Draft: Foxy-devel

### PR DESCRIPTION
**Pull request by relffok**
Hi there, 

I started porting this to foxy a while ago. I also needed to port the tests, so there is no qualified statement whether this works as intended or not. I use it for the mir_bridge (see https://github.com/dfki-ric/mir_robot/pull/96) and it does it's job. 
I'm sure there will be some issues (there are 2 failures I could not fix so far but unfortunately ported this a while ago and forgot about the PR), so feedback would be great on this! 

Also since I renamed the package from `rospy_message_converter` to `rclpy_message_converter` I think a little bit of git history went missing. Sorry about that.

### CODE REVIEW

**Comment by mintar** [comment]
Thanks for the PR! I'll look into it as soon as I find the time!

**Comment by rcywongaa** [comment]
FWIW, this is also working on galactic :+1: 

```
        goal_msg.trajectory.points = [
          message_converter.convert_dictionary_to_ros_message('trajectory_msgs/JointTrajectoryPoint',
          {
            "positions": [0.2, 0.0, 0.0, 0.0, 0.0, 0.0],
            "time_from_start": [1, 0]
          })
        ]
```
(http://docs.ros.org/en/api/trajectory_msgs/html/msg/JointTrajectoryPoint.html)
Thanks a lot for doing this!  Hope this gets merged soon! :muscle:

**Comment by mintar** [comment]
> this doesn't work
> "time_from_start": Duration(seconds=1)

That's not supposed to work. `convert_dictionary_to_ros_message` converts a JSON-like dictionary to a ROS message, and there should be only basic datatypes (string, int, float, ...) in there. `Duration` is not a basic datatype.

> this is also working
> "time_from_start": [1, 0]

Maybe that works, but I think a better way would be this:

```python
    "time_from_start": {"sec": 1, "nanosec": 0}
```

**Comment by mintar** [comment]
I have just finished converting this repo to ROS2 and released it (as `rclpy_message_converter`) to ROS2 foxy, galactic, humble and rolling. It should be available as binary package after the next sync.

I used as much as I could from this PR (thanks a lot, @relffok!). I ended up re-doing a lot of it in order to keep the Git history and have nice commits. Also, I've ended up copying and modifying [rosidl_runtime_py.set_message.set_message_fields()](https://github.com/ros2/rosidl_runtime_py/blob/1979f566c3b446ddbc5c3fb6896e1f03ccbc6a27/rosidl_runtime_py/set_message.py#L28-L37) and [rosidl_runtime_py.convert.message_to_orderreddict](https://github.com/ros2/rosidl_runtime_py/blob/1979f566c3b446ddbc5c3fb6896e1f03ccbc6a27/rosidl_runtime_py/convert.py#L159-L176) instead of adapting the old implementation.

The biggest thing that was missing from this PR (and from the `rosidl_runtime_py` implementations above) is the Base64 encoding of binary arrays (`uint8[]`). I haven't checked, but I'm pretty sure that the `mir_robot` driver transfers `sensor_msgs/Image` encoded this way. I've added back this functionality.

It now passes all the original tests, so I'm very confident that it works just as before.

**Comment by relffok** [comment]
Awesome, thank you. Glad I could contribute and looking forward to using it.

**Comment by mintar** [comment]
Thanks again. Without you taking the initiative I wouldn't have done it.

**Pull request closed without merging**
