### PR TITLE
Add check_types parameter to convert_dictionary_to_ros_message

### PR DESCRIPTION
**Pull request by mintar**

### CODE REVIEW

**Comment by mintar** [comment]
@ichumuh: Here's the check_types parameter that we discussed in #41. I think I'll leave the default as `True` unless you convince me otherwise. :)

The reason why I think it's a better default is that most people probably won't change the default. If that later raises an error, they can make a conscious decision if they want to fix the types or disable the check.

**Comment by ichumuh** [comment]
> The reason why I think it's a better default is that most people probably won't change the default. If that later raises an error, they can make a conscious decision if they want to fix the types or disable the check.

Fair enough.

**Comment by ichumuh** [comment]
Thanks for this pr @mintar and sorry for using the old thread. But I'd like to know when v0.5.3 will be released.

**Comment by mintar** [comment]
My release PRs were merged 15-21 days ago:

https://github.com/ros/rosdistro/pull/26253
https://github.com/ros/rosdistro/pull/26254
https://github.com/ros/rosdistro/pull/26255

Kinetic and Noetic both already have 0.5.3, Melodic will probably get it this week: https://discourse.ros.org/t/preparing-for-melodic-sync-2020-08-19/15988/6

**Comment by ichumuh** [comment]
Thanks for the info!

**Pull request merged**
